services:
  - type: web
    name: furia-bot
    env: node
    region: oregon
    plan: free
    buildCommand: >
      apt-get update &&
      apt-get install -y chromium &&
      export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium &&
      npm install --legacy-peer-deps &&
      npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
    buildFilter:
      paths:
        - src/**
        - package.json
        - server.js
        - vite.config.ts
        - tsconfig.json
    autoDeploy: true